packages:
  - backend
  - frontend
  - shared
  - functions

ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - re2
  - sharp
